#!/usr/bin/env bash

function error_and_die() {
  echo -e "tfenv: $(basename ${0}): \033[0;31m[ERROR] ${1}\033[0;39m" >&2
  exit 1
}

function warn_and_continue() {
  echo -e "tfenv: $(basename ${0}): \033[0;33m[WARN] ${1}\033[0;39m" >&2
}

function info() {
  echo -e "\033[0;32m[INFO] ${1}\033[0;39m"
}

# Curl wrapper to switch TLS option for each OS
function curlw () {
  local TLS_OPT="--tlsv1.2"

  # Check if curl is 10.12.6 or above
  if [[ -n "$(which sw_vers 2>/dev/null)" && ("$(sw_vers)" =~ 10\.12\.([6-9]|[0-9]{2}) || "$(sw_vers)" =~ 10\.1[3-9]) ]]; then
    TLS_OPT=""
  fi

  curl ${TLS_OPT} "$@"
}

function get_version_requested () {
  if [ -z "${1}" ]; then
    version_file="$(tfenv-version-file)"
    if [ "${version_file}" != "${TFENV_ROOT}/version" ];then
      version_requested="$(cat "${version_file}" || true)"
    fi
  else
    version_requested="${1}"
  fi

  if [[ "${version_requested}" =~ ^min-required$ ]]; then
    echo "Detecting minimal required version..."
    found_min_required="$(tfenv-min-required)"

    if [[ $? -eq 0 ]]; then
      echo "Min required version is detected as ${found_min_required}"
      version_requested=${found_min_required}
    else
      exit 1
    fi
  fi
}

