#!/usr/bin/env bash

function color_echo() {
  local color_code="${1}"
  if [ -z "${TFENV_NO_COLOR}" ]
  then
    echo -en "\033[${color_code}m"
    echo -n "${2}"
    echo -e "\033[0;39m"
  else
    echo "${2}"
  fi
}

function error_and_die() {
  echo -n "tfenv: $(basename ${0}): " >&2
  color_echo "0;31" "[ERROR] ${1}" >&2
  exit 1
}

function warn_and_continue() {
  echo -n "tfenv: $(basename ${0}): " >&2
  color_echo "0;33" "[WARN] ${1}" >&2
}

function info() {
  color_echo "0;32" "[INFO] ${1}"
}

# Curl wrapper to switch TLS option for each OS
function curlw () {
  local TLS_OPT="--tlsv1.2"

  # Check if curl is 10.12.6 or above
  if [[ -n "$(command -v sw_vers 2>/dev/null)" && ("$(sw_vers)" =~ 10\.12\.([6-9]|[0-9]{2}) || "$(sw_vers)" =~ 10\.1[3-9]) ]]; then
    TLS_OPT=""
  fi

  curl ${TLS_OPT} "$@"
}
