#!/usr/bin/env bash

[ -n "${TFENV_DEBUG}" ] && set -x
source ${TFENV_ROOT}/libexec/helpers

[ ${#} -ne 0 ] \
  && error_and_die "usage: tfenv list"

[ -d "${TFENV_ROOT}/versions" ] \
  || error_and_die "No versions available. Please install one with: tfenv install"

[[ -x "${TFENV_ROOT}/versions" && -r "${TFENV_ROOT}/versions" ]] \
  || error_and_die "tfenv versions directory is inaccessible!"

ls -1 "${TFENV_ROOT}/versions" | sort -t'.' -k 1nr,1 -k 2nr,2 -k 3nr,3
