#!/usr/bin/env bash
set -e
[ -n "${TFENV_DEBUG}" ] && set -x
source ${TFENV_ROOT}/libexec/helpers

if [ ${#} -ne 0 ];then
  echo "usage: tfenv list-remote" 1>&2
  exit 1
fi

curlw -sf https://releases.hashicorp.com/terraform/ | awk -F"[ /]" '/terraform/ && ! /(alpha|beta|rc)/ {print $8}'
