#!/usr/bin/env bash
# Usage: tfenv min-required
# Summary: Detect the minimal required version from *tf files

set -uo pipefail;

# Ensure we can execute standalone
if [ -n "${TFENV_ROOT:-""}" ]; then
  if [ "${TFENV_DEBUG:-0}" -gt 1 ]; then
    [ -n "${TFENV_HELPERS:-""}" ] \
      && log 'debug' "TFENV_ROOT already defined as ${TFENV_ROOT}" \
      || echo "[DEBUG] TFENV_ROOT already defined as ${TFENV_ROOT}" >&2;
  fi;
else
  export TFENV_ROOT="$(cd "$(dirname "${0}")/.." && pwd)";
  if [ "${TFENV_DEBUG:-0}" -gt 1 ]; then
    [ -n "${TFENV_HELPERS:-""}" ] \
      && log 'debug' "TFENV_ROOT declared as ${TFENV_ROOT}" \
      || echo "[DEBUG] TFENV_ROOT declared as ${TFENV_ROOT}" >&2;
  fi;
fi;

if [ -n "${TFENV_HELPERS:-""}" ]; then
  log 'debug' 'TFENV_HELPERS is set, not sourcing helpers again';
else
  [ "${TFENV_DEBUG:-0}" -gt 1 ] && echo "[DEBUG] Sourcing helpers from ${TFENV_ROOT}/lib/helpers.sh" >&2;
  if source "${TFENV_ROOT}/lib/helpers.sh"; then
    log 'debug' 'Helpers sourced successfully';
  else
    echo "[ERROR] Failed to source helpers from ${TFENV_ROOT}/lib/helpers.sh" >&2;
    exit 1;
  fi;
fi;

bailout() {
  log 'error' 'Error: Could not determine required_version based on your terraform sources.
Make sure at least one of your *tf files includes a required version section like
terraform {
  required_version = ">= 0.0.0"
}

see https://www.terraform.io/docs/configuration/terraform.html for details';
};

find_min_required() {
  local root="${1}";

  versions="$(grep -h -R required_version --include '*tf' "$root"/* | tr -c -d '0-9. ~=!<>' )";

  if [[ "${versions}" =~ ([~=!<>]{0,2}[[:blank:]]*[0-9]+[0-9.]+)[^0-9]* ]]; then
    found_min_required="${BASH_REMATCH[1]}";

    if [[ "${found_min_required}" =~ ^!=.+ ]]; then
      log 'debug' "Error: Min required version is a negation ($found_min_required) - we cannot guess the desired one.";
      bailout;
    else
      found_min_required="$(echo "$found_min_required" | tr -c -d '0-9.')";
      #echo "Min required version is detected as ${found_min_required}";
      echo "${found_min_required}";
      exit 0;
    fi;
  fi;

  bailout;
};

find_min_required "${TFENV_DIR}";
