#!/usr/bin/env bash
# Usage: tfenv version-file
# Summary: Detect the file that sets the current tfenv version
set -e
[ -n "${TFENV_DEBUG}" ] && set -x

find_local_version_file() {
  local root="${1}"
  while ! [[ "${root}" =~ ^//[^/]*$ ]]; do

    if [ -e "${root}/backend.tf" ]; then
      version=$(grep required_version "${root}"/backend.tf | tr -dcs '0-9.' '')

      if [[ ! -z "$version" ]]; then
        echo "$version" > "${root}/.terraform-version"
      fi

    fi

    if [ -e "${root}/.terraform-version" ]; then
      echo "${root}/.terraform-version"
      return 0
    fi
    [ -n "${root}" ] || break
    root="${root%/*}"
  done
  return 1
}

find_local_version_file "${TFENV_DIR}" || find_local_version_file "${HOME}" || echo "${TFENV_ROOT}/version"
