#!/usr/bin/env bash
set -e
[ -n "$TFENV_DEBUG" ] && set -x

if [ $# -ne 1 ];then
  echo "usage: tfenv use <version>" 1>&2
  exit 1
fi

version="${1}"
if [ -z "${version}" ];then
  echo "version is not specified" 1>&2
  exit 1
fi

target_path=${TFENV_ROOT}/versions/${version}
if [ ! -f ${target_path}/terraform ];then
  echo "${version} is not installed" 1>&2
  exit 1
fi

echo "${version}" > "${TFENV_ROOT}/version"
terraform --version
