#!/usr/bin/env bash

set -uo pipefail;

echo 'Usage: tfenv <command> [<options>]

Commands:
   install       Install a specific version of Terraform
   use           Switch a version to use
   uninstall     Uninstall one or more versions of Terraform
   list          List all installed versions
   list-remote   List all installable versions
   version-name  Print current version
   init          Update environment to use 'tfenv' correctly.
   pin           Write the current active version to ./.terraform-version
';

exit 0;
