#!/usr/bin/env bash

[ -n "${TFENV_DEBUG}" ] && set -x
source "${TFENV_ROOT}/libexec/helpers"

[ "${#}" -ne 0 ] \
  && error_and_die "usage: tfenv list"

[ -d "${TFENV_ROOT}/versions" ] \
  || error_and_die "No versions available. Please install one with: tfenv install"

[[ -x "${TFENV_ROOT}/versions" && -r "${TFENV_ROOT}/versions" ]] \
  || error_and_die "tfenv versions directory is inaccessible!"

print_version () {
    if [ "${1}" == "$(tfenv-version-name)" ]; then
        echo "* ${1} (set by $(tfenv-version-file))"
    else
        echo "  ${1}"
    fi
}

versions="$(find "${TFENV_ROOT}/versions" -type d -exec basename {} \; \
  | tail -n +2 \
  | sort -t'.' -k 1nr,1 -k 2nr,2 -k 3nr,3)"

for local_version in ${versions}; do
    print_version "${local_version}"
done
