#!/usr/bin/env bash
# Summary: Show the current Terraform version
set -e
[ -n "$TFENV_DEBUG" ] && set -x

TFENV_VERSION_FILE="$(tfenv-version-file)"
TFENV_VERSION="$(cat "$TFENV_VERSION_FILE" || true)"

if [ -z "$TFENV_VERSION" ]; then
  echo "tfenv: version could not be resolved (set by $TFENV_VERSION_FILE or tfenv use <version>)" >&2
  exit 1
fi

version_exists() {
  local version="$1"
  [ -d "${TFENV_ROOT}/versions/${version}" ]
}

if version_exists "$TFENV_VERSION"; then
  echo "$TFENV_VERSION"
else
  echo "tfenv: version \`$TFENV_VERSION' is not installed (set by $TFENV_VERSION_FILE)" >&2
  exit 1
fi
