#!/usr/bin/env bash
#
# Summary: Run an executable with the selected Terraform version
#
# Usage: tfenv exec <command> [arg1 arg2...]
#
# Runs an executable by first preparing PATH so that the selected Terraform
# version's `bin' directory is at the front.
#
# For example, if the currently selected Terraform version is 0.7.0:
#   tfenv exec plan
#
# is equivalent to:
#   PATH="$TFENV_ROOT/versions/0.7.0/bin:$PATH" terraform plan

set -e
[ -n "${TFENV_DEBUG}" ] && set -x

export TFENV_VERSION="$(tfenv-version-name)"
TF_BIN_PATH="${TFENV_ROOT}/versions/${TFENV_VERSION}/terraform"
export PATH="${TF_BIN_PATH}:${PATH}"
"${TF_BIN_PATH}" "${@}"
