name: 'Go Edition Release'

on:
  push:
    tags:
      - 'go/v*'

permissions:
  contents: write
  packages: write

jobs:

  release:
    name: 'Release'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v4'
        with:
          fetch-depth: 0
      - uses: 'actions/setup-go@v5'
        with:
          go-version-file: 'go/go.mod'
          cache-dependency-path: 'go/go.sum'
      - uses: 'goreleaser/goreleaser-action@v6'
        with:
          distribution: 'goreleaser'
          version: '~> v2'
          args: 'release --clean'
          workdir: 'go'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
